### ISSUE TITLE
settings.version attribute doesn't exist & connect_retry_interval=60 ignored

### ISSUE THREAD

**Issue by adrianlop** [google-terraform-modules/terraform-google-cloudsql-ha#3]
hi @perriea ,

I can successfully create a SQL-HA with this module, however when terraform finishes, I get the following error:
```
* module.cloudsql-ha-tigase.output.master_settings_version: Resource 'google_sql_database_instance.new_instance_sql_master' does not have attribute 'settings.version' for variable 'google_sql_database_instance.new_instance_sql_master.settings.version'
* module.cloudsql-ha-tigase.output.replica_settings_version: Resource 'google_sql_database_instance.new_instance_sql_replica' does not have attribute 'settings.version' for variable 'google_sql_database_instance.new_instance_sql_replica.settings.version'
* module.cloudsql-ha-tigase.output.replica_instance_sql_setting_version: Resource 'google_sql_database_instance.new_instance_sql_replica' does not have attribute 'settings.version' for variable 'google_sql_database_instance.new_instance_sql_replica.settings.version'
* module.cloudsql-ha-tigase.output.master_instance_sql_setting_version: Resource 'google_sql_database_instance.new_instance_sql_master' does not have attribute 'settings.version' for variable 'google_sql_database_instance.new_instance_sql_master.settings.version'
```

this is the tf I used:

```
module "cloudsql-ha-tigase" {
  source  = "google-terraform-modules/cloudsql-ha/google"
  version = "1.8.0"

  name           = "tigase"
  env            = "${var.environment}"
  region         = "${var.region}"
  cidr_ip_access = "0.0.0.0/0"

  database_version      = "MYSQL_5_7"
  instance_size_master  = "db-f1-micro"
  instance_size_replica = "db-f1-micro"
  disk_size             = "10"
  zone_master           = "b"
  zone_replica          = "c"
  disk_autoresize       = true
}
```

I'm using google provider version 1.12.0

Also, another bug:
https://github.com/google-terraform-modules/terraform-google-cloudsql-ha/blob/master/variables.tf#L98-L102
This default is ignored at the creation time, instead of 60, is set to 0.
doing a `terraform plan` after the creation, shows that it's going to recreate the replica:
`replica_configuration.0.connect_retry_interval: "0" => "60" (forces new resource)`

had to set it to 0 for now to avoid destroy/create

I guess this is happening because the module was only compatible with provider `1.8.0`. Are you planning to support newer provider versions?

thanks in advance!

**Comment by perriea** [comment]
Hi @adrianlop,
An update is planned for the latest version of the provider (very soon).
However, `replica_configuration.0.connect_retry_interval bug: "0" => "60" (forces new resource)` is still present at my development stage.

It is possible that the value `0` is now forbidden.
I will have to look in the provider code.

The next format will be similar of GKE (https://github.com/google-terraform-modules/terraform-google-kubernetes-engine).
```
module "cloudsql" {
  source = "./terraform-google-cloudsql-ha"

  general = {
    name       = "apps2"
    env        = "dev"
    region     = "europe-west1"
    db_version = "MYSQL_5_6"
  }

  master = {
    zone = "b"
  }

  replica = {
    zone = "c"
  }
}
```

Happy Terraforming :)

**Comment by perriea** [comment]
After tests, I think there is a problem with the provider.
I try to put the hard value but I still have the same problem ...

I do not see any problem in the code
https://github.com/terraform-providers/terraform-provider-google/blob/c6b0cfcbfae622f46da1c0ece9ac76cfa373dbd3/google/resource_sql_database_instance.go#L322

I will ignore the value for the moment and look into the issue. 
If it does not exist I will open an issue on the Google provider.

**Comment by adrianlop** [comment]
nice one @perriea will have a look when I have some time. thanks!
